# Generated by Django 3.0.9 on 2022-06-26 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_logoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.LogoImage'),
        ),
    ]
