# Generated by Django 3.0.9 on 2022-07-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20220721_0640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
