# Generated by Django 3.0.9 on 2022-07-21 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20220611_1739'),
        ('links', '0006_auto_20220721_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
    ]
